export const UPDATE_STORES = "UPDATE_STORES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const OPEN_MODAL = 'OPEN_MODAL';
export const UPDATE_MALLS = "UPDATE_MALLS";